"""Source-reviewed additions. Existing product policies are intentionally preserved."""
from pathlib import Path
from html import escape
from app_documents import APPS, TYPES
ROOT = Path(__file__).resolve().parents[1]
DOCS = {
 ('jxl-scheduler','terms'): [
 ('scope','Use and scope','JxL Scheduler helps you organize schedules, routes, messages, and uploads on your device, with optional group sharing through iCloud. These terms apply to that application, not to an employer’s scheduling or employment agreement.'),
 ('responsibilities','Your responsibilities','Use the app lawfully and only share material you are entitled to share. Obtain permission before sharing another person’s location, messages, or documents. Do not use shared groups to harass others or access information without authorization.'),
 ('sharing','Shared information','You retain your rights in content you create. Inviting people to an iCloud group makes shared content available to those participants. Review group membership and permissions before sharing sensitive information. Removing access cannot recall copies someone has already made.'),
 ('availability','Availability and operational decisions','Device storage, permissions, connectivity, and iCloud availability affect the experience. Confirm important schedules and routes independently; do not rely on the app for emergency response. Keep separate copies of records needed for your operations. These terms do not promise uninterrupted service or a particular delivery time.'),
 ('rights','Software and third-party services','The app’s availability does not transfer ownership of its software or branding. Apple’s applicable iCloud and distribution terms also apply to those services. Nothing on this page limits rights that cannot be excluded under applicable law.'),
 ('contact','Questions','For application help, contact support@edentv.us. For questions about these terms, contact legal@edentv.us. Include the app name and version, but not private schedules or credentials.')],
 ('kasapa','privacy'): [
 ('scope','Current prototype','This notice describes Kasapa’s Milestone 3 on-device prototype. It has no network backend or account server. Names, connections, and conversations in the prototype are local application records; they are not a live professional network.'),
 ('data','Information stored on the device','The app stores profile and business details, cards, connection states, exact sharing grants, local messages and conversation metadata, reports, and action history. The persistence layer writes a JSON snapshot in the app’s Application Support storage.'),
 ('sharing','How sharing works','Discovery searches public name, headline, company, and discoverable tags. Private fields and individual cards require a connected relationship and the corresponding directional grant. These controls govern visibility within the local prototype; accepting a connection does not transmit data to a remote person.'),
 ('controls','Your controls and retention','You can edit profiles and cards, change sharing grants, remove connections, block peers, and delete a local conversation thread. Blocking revokes grants and hides conversations but retains messages and local report/action history. Unblocking does not restore the connection or its grants. The reviewed implementation does not establish a timed automatic deletion schedule.'),
 ('services','Services and support contact','The reviewed prototype uses on-device persistence and no third-party packages. This notice does not make a claim about Apple’s device backup services. If you email support, the information you choose to send is handled through email, separately from app storage. Send only what is needed to explain the issue.'),
 ('contact','Privacy questions','Contact privacy@edentv.us with the Kasapa version and a description of your question. EdenTV cannot remotely retrieve or erase records from this local-only prototype. Avoid sending private messages, contact lists, or credentials.')],
 ('kasapa','terms'): [
 ('scope','Prototype terms','Kasapa is an experimental, on-device professional-networking interface. It is not a live messaging service, identity-verification service, or directory of real people. Use sample information when exploring it.'),
 ('conduct','Acceptable use','Only enter information you are authorized to use. Do not impersonate others, harass people, or use the prototype to store or distribute unlawful material. Local block and report controls do not contact a remote moderation team.'),
 ('content','Your content and software rights','You retain rights in the content you enter. Using the prototype does not transfer ownership of its software or branding. Granting local profile access is a visibility choice, not a transfer of content ownership.'),
 ('limits','Limitations','Messages, connection requests, and reports stay within the local application model. They are not delivered to another device. Experimental changes may affect stored data; keep important information elsewhere. No uninterrupted availability, remote delivery, or recovery service is promised.'),
 ('contact','Help and terms questions','Contact support@edentv.us for prototype help or legal@edentv.us for questions about these terms. These terms do not remove rights that cannot be excluded by applicable law.')],
 ('kasapa','support'): [
 ('getting-started','Getting started','Use the supplied prototype build and complete the local profile flow. Discover, Network, Messages, and Profile operate on the local data model. An internet connection does not turn the prototype into a multi-device network.'),
 ('sharing','Connections and sharing','Accept an incoming request to create a connection, then check exactly which fields or cards are shared. Sharing is directional: sharing your own field does not reveal another profile’s private field. A missing private detail may mean no matching grant exists.'),
 ('messaging','Messages','Open Messages or a connected profile to compose. Messaging requires a connected relationship. Messages are local records, not remotely delivered messages or read receipts. Deleting a thread requires confirmation.'),
 ('blocking','Blocking and reports','Manage blocked peers from Profile → Blocked accounts. Blocking removes both-direction grants and hides the peer from ordinary lists. Unblocking returns the relationship to neutral; reconnect and review grants explicitly. Reports are stored locally and are not submitted to a moderation service.'),
 ('troubleshooting','Troubleshooting','If expected information is absent, check the connection state and sharing grants first. Record the version, device/OS, action taken, and visible error. Preserve important data before reinstalling or replacing a prototype build; do not assume a server copy exists.'),
 ('contact','Contact support','Email support@edentv.us with Kasapa in the subject and steps to reproduce the issue. Redact private profile fields and messages from screenshots. Never send credentials.')],
 ('kasapa','compliance'): [
 ('status','Review status','These are preparation notes for Kasapa’s Milestone 3 prototype, not a statement of App Store submission, approval, or compliance certification. Distribution readiness must be assessed against the actual submitted build.'),
 ('architecture','Current behavior','The reviewed app is a native SwiftUI prototype with local JSON persistence, no network backend, no account server, and no third-party packages. Profile sharing, messaging, block/report, and action history operate locally.'),
 ('review-flow','Suggested review flow','Complete local onboarding; inspect Discover; send and accept an eligible incoming connection; change an exact field/card grant; open a connected conversation; delete a thread; block and unblock a peer. Confirm that unblocking restores neither grants nor the former connection.'),
 ('safety','Safety and messaging boundaries','Local reports do not reach a human moderation service. Messages have no remote delivery or read receipts. A production social service would need separate assessment of moderation, abuse handling, account lifecycle, and data disclosures before release.'),
 ('submission','Before submission','Check the release build’s permissions, bundled SDKs, privacy disclosures, screenshots, support URLs, and any account/deletion flows. Review these notes whenever networking or third-party services are added; do not reuse the local-only description for a changed architecture.'),
 ('contact','Review contact','For build-specific questions contact support@edentv.us. State the build number and review step. This public page contains no reviewer credentials.')],
}
for (slug,kind), sections in DOCS.items():
 name,anchor,_=APPS[slug];title=f'{name} {TYPES[kind]}'
 links=''.join(f'<a href="/docs/{slug}-{k}">{label}</a>' for k,label in TYPES.items())
 body=''.join(f'<section id="{id}" class="doc-section"><h2>{escape(h)}</h2><p>{escape(text)}</p></section>' for id,h,text in sections)
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} - EdenTV</title><meta name="description" content="{escape(sections[0][2], quote=True)}"><link rel="stylesheet" href="/css/styles.css?v=20261002"></head><body class="page-docs"><main class="container app-document"><nav aria-label="Breadcrumb"><a href="/pages/apps">Apps</a> / <a href="/pages/developer-docs#{anchor}">{name} documents</a></nav><header><p class="eyebrow">{name}</p><h1>{title}</h1><p class="last-updated">Last reviewed: <time datetime="2026-10-02">October 2, 2026</time></p><nav class="project-actions" aria-label="{name} documents">{links}</nav></header><div class="doc-body">{body}</div><footer><a href="/pages/developer-docs">All documents &amp; support</a></footer></main></body></html>'''
 (ROOT/'docs'/f'{slug}-{kind}.html').write_text(html+'\n')

# Product overviews connect cards to the same four supporting documents.
for slug, (name, anchor, description) in APPS.items():
 if slug == 'pulsetrackr':
  continue  # Preserve the existing, richer product overview.
 links = ''.join(f'<a class="document-row" href="/docs/{slug}-{kind}"><strong>{label}</strong><span aria-hidden="true">→</span></a>' for kind,label in TYPES.items())
 scope = 'Local-only prototype. No remote messaging, account server, or App Store release is implied.' if slug == 'kasapa' else 'Local-first iPhone application with optional iCloud sharing. See the support guide for setup and current behavior.'
 (ROOT/'pages'/f'{slug}.html').write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{name} - EdenTV</title><meta name="description" content="{description}"><link rel="stylesheet" href="/css/styles.css?v=20261002"></head><body><main class="container app-document"><a href="/pages/apps">← All apps</a><header><p class="eyebrow">iOS application</p><h1>{name}</h1><p>{description}</p><p>{scope}</p></header><section><h2>Documents &amp; support</h2><div class="document-index">{links}</div></section><p><a href="mailto:support@edentv.us">Contact product support</a></p></main></body></html>\n')
